make: Even more build tweaks
DCO-1.1-Signed-off-by: Ellie <el@horse64.org>

diff --git a/Dockerfile.build-x64 b/Dockerfile.build-x64
--- a/Dockerfile.build-x64
+++ b/Dockerfile.build-x64
@@ -4,7 +4,7 @@ FROM ubuntu:22.04
 ENV DEBIAN_FRONTEND=noninteractive
 RUN apt update --fix-missing
 RUN apt -y install wine git git-lfs vim make autoconf libtool cmake libxinerama-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxkbcommon-dev libxcb-xv0-dev x11-xserver-utils perl rsync zip unzip libwayland-dev libxext-dev libxcb-xinput-dev libpulse-dev libasound2-dev valgrind gdb gcc g++ g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64 python3 pip
-RUN apt -y install libwayland-egl-backend-dev tzdata libwayland-cursor0 wayland-scanner++ waylandpp-dev libwayland-cursor0 wayland-scanner++ mlocate
+RUN apt -y install libwayland-egl-backend-dev tzdata libwayland-cursor0 wayland-scanner++ waylandpp-dev libwayland-cursor0 wayland-scanner++ mlocate libudev-dev
 RUN python3 -m pip install -U wheel requests Cython pywildcard
 RUN python3 -m pip install -U pip
 RUN apt update && apt install -y ca-certificates
@@ -22,14 +22,29 @@ RUN echo "#!/bin/bash\n\
     }\n\
     git submodule update --init || { echo 'Failed submodule init.'; exit 1; }\n\
     make veryclean\n\
+    echo ''\n\
+    echo 'Starting Windows x64 builds...'\n\
+    echo '=============================='\n\
     make build-windows-x64 || { echo 'Failed windows build.'; exit 1; }\n\
-    cp ./output/*.exe ../volume-output/\n\
-    cp ./output/*.dll ../volume-output/\n\
+    echo 'Copying Windows x64 build result...'\n\
+    cp ./output/HVM.exe ../volume-output/HVM.Windows-x64.exe\n\
+    cp ./output/HVM-headless.exe ../volume-output/HVM-headless.Windows-x64.exe\n\
+    cp ./output/HVM.dll ../volume-output/HVM.Windows-x64.dll\n\
+    cp ./output/HVM-headless.dll ./volume-output/HVM-headless.Windows-x64.exe\n\
+    echo ''\n\
+    echo 'Cleaning up...'\n\
+    echo '=============='\n\
     make veryclean\n\
-    make build-deps || { echo 'Failed to rebuild deps.'; exit 1; }\n\
+    echo ''\n\
+    echo 'Starting Linux x64 build...'\n\
+    echo '==========================='\n\
+    make build-deps-graphical || { echo 'Failed to rebuild deps.'; exit 1; }\n\
     make || { echo 'Failed Linux build.'; exit 1; }\n\
-    cp ./output/*.bin ../volume-output/\n\
-    cp ./output/*.so ../volume-output/\n\
+    echo 'Copying Linux x64 build result...'\n\
+    cp ./output/HVM.bin ../volume-output/HVM.Linux-x64-glib.bin\n\
+    cp ./output/HVM-headless.bin ../volume-output/HVM-headless.Linux-x64-glib.bin\n\
+    cp ./output/HVM.so ../volume-output/HVM.Linux-x64-glib.so\n\
+    cp ./output/HVM-headless.so ../volumes-output/HVM-headless.Linux-x64-glib.so\n\
     echo 'Done!'" > /home/hvm.horse64.org/docker-build.sh
 VOLUME /home/hvm.horse64.org/build/
 
